import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    username: { type: String, required: true, unique: true },
    // Encrypted at rest (RSA) — decrypt only when an admin with proper
    // privilege needs to view it; never expose raw in API responses.
    emailEncrypted: { type: String, required: true },
    contactInfoEncrypted: { type: String },

    passwordHash: { type: String, required: true },
    passwordSalt: { type: String, required: true },
    // Set true when an admin creates this account (they know the initial
    // password), cleared once the user sets their own via /auth/password.
    mustChangePassword: { type: Boolean, default: false },

    role: { type: String, enum: ["reporter", "reviewer", "admin"], default: "reporter" },

    // 2FA — a secret generated by setup2FA sits in totpSecretPending until
    // the user proves (via confirm2FA) they actually scanned the QR code;
    // only then does it become the active totpSecret and is2FAEnabled flip
    // on. This avoids a user locking themselves out by enabling 2FA against
    // a code they never actually captured.
    totpSecret: { type: String },
    totpSecretPending: { type: String },
    is2FAEnabled: { type: Boolean, default: false },

    // Public keys only — private keys live in a separate, tightly-restricted collection
    rsaPublicKey: { type: mongoose.Schema.Types.Mixed },
    eccPublicKey: { type: mongoose.Schema.Types.Mixed },

    createdAt: { type: Date, default: Date.now },
  },
  { timestamps: true }
);

export default mongoose.model("User", userSchema);